export default class ImageUtil {
  static images = {
    ic_heart: require('../assets/icons/ic_heart.png'),
    ic_heart_active: require('../assets/icons/ic_heart_active.png'),
    ic_like: require('../assets/icons/ic_like.png'),
    ic_unlike: require('../assets/icons/ic_unlike.png'),
    ic_close: require('../assets/icons/ic_close.png'),
    ic_star: require('../assets/icons/ic_star.png'),
    ic_send: require('../assets/icons/ic_send.png'),
    bg_linear: require('../assets/icons/bg_linear.png'),
    ic_reload: require('../assets/icons/ic_reload.png'),
    ic_location: require('../assets/icons/ic_location.png'),
    ic_profile_inactive: require('../assets/icons/ic_profile_inactive.png'),
    ic_profile_active: require('../assets/icons/ic_profile_active.png'),
    ic_messages_inactive: require('../assets/icons/ic_messages_inactive.png'),
    ic_home_active: require('../assets/icons/ic_home_active.png'),
    ic_home_inactive: require('../assets/icons/ic_home_inactive.png'),
    ic_category_inactive: require('../assets/icons/ic_category_inactive.png'),
    ic_category_active: require('../assets/icons/ic_category_active.png'),
    ic_messages_active: require('../assets/icons/ic_messages_active.png'),
    ic_match_active: require('../assets/icons/ic_match_active.png'),
    ic_match_inactive: require('../assets/icons/ic_match_inactive.png'),
    ic_arrow_up: require('../assets/icons/ic_arrow_up.png'),
    ic_thunder: require('../assets/icons/ic_thunder.png'),
  };
}
